import type { ThemeOptions } from "@mui/material/styles";
import { displayFont, bodyFont } from "./tokens";

export const typography: ThemeOptions["typography"] = {
  fontFamily: bodyFont,
  h1: {
    fontFamily: displayFont,
    fontWeight: 700,
    fontSize: "clamp(2.5rem, 1.6rem + 2.2vw, 4.25rem)",
    lineHeight: 1.05,
    letterSpacing: "-0.04em",
    textWrap: "balance" as unknown as string,
  },
  h2: {
    fontFamily: displayFont,
    fontWeight: 700,
    fontSize: "clamp(2rem, 4vw, 3rem)",
    lineHeight: 1.1,
    letterSpacing: "-0.025em",
    textWrap: "balance" as unknown as string,
  },
  h3: {
    fontFamily: displayFont,
    fontWeight: 700,
    fontSize: "clamp(1.5rem, 3vw, 2.25rem)",
    lineHeight: 1.15,
    letterSpacing: "-0.02em",
    textWrap: "balance" as unknown as string,
  },
  h4: {
    fontFamily: displayFont,
    fontWeight: 700,
    fontSize: "clamp(1.25rem, 2vw, 1.5rem)",
    lineHeight: 1.2,
    letterSpacing: "-0.015em",
    textWrap: "balance" as unknown as string,
  },
  h5: {
    fontFamily: displayFont,
    fontWeight: 700,
    fontSize: "1.25rem",
    lineHeight: 1.3,
    letterSpacing: "-0.01em",
  },
  h6: {
    fontFamily: displayFont,
    fontWeight: 700,
    fontSize: "1rem",
    lineHeight: 1.4,
    letterSpacing: "-0.01em",
  },
  body1: {
    fontFamily: bodyFont,
    fontSize: "1rem",
    lineHeight: 1.6,
    letterSpacing: "-0.015em",
    fontWeight: 400,
  },
  body2: {
    fontFamily: bodyFont,
    fontSize: "0.875rem",
    lineHeight: 1.6,
    letterSpacing: "-0.005em",
    fontWeight: 400,
  },
  subtitle1: {
    fontFamily: bodyFont,
    fontSize: "1rem",
    lineHeight: 1.5,
    letterSpacing: "-0.01em",
    fontWeight: 500,
  },
  subtitle2: {
    fontFamily: bodyFont,
    fontSize: "0.875rem",
    lineHeight: 1.5,
    letterSpacing: "-0.005em",
    fontWeight: 500,
  },
  button: {
    fontFamily: bodyFont,
    textTransform: "none",
    fontWeight: 500,
    letterSpacing: "-0.01em",
    lineHeight: 1.2,
  },
  caption: {
    fontFamily: bodyFont,
    fontSize: "0.75rem",
    lineHeight: 1.5,
    letterSpacing: "0",
  },
  overline: {
    fontFamily: bodyFont,
    fontSize: "0.75rem",
    lineHeight: 1.5,
    letterSpacing: "0.05em",
    fontWeight: 600,
    textTransform: "uppercase" as const,
  },
};
